:: TeX related commands
call tlmgr install inputenc
call tlmgr install amsmath
call tlmgr install amssymb
call tlmgr install graphicx
call tlmgr install color
call tlmgr install enumerate
call tlmgr install float
call tlmgr install capt-of
call tlmgr install sidecap
call tlmgr install caption
call tlmgr install commath
call tlmgr install cancel
call tlmgr install anysize
call tlmgr install appendix
call tlmgr install tocbibind
call tlmgr install tabularx
call tlmgr install babel
call tlmgr install indentfirst
call tlmgr install biblatex
call tlmgr install emoji
call tlmgr install csquotes
call tlmgr install multirow
call tlmgr install algorithm2e
call tlmgr install enumitem
call tlmgr install changepage
call tlmgr install alltt
call tlmgr install lmodern
call tlmgr install gensymb
call tlmgr install subcaption
call tlmgr install hyperref
call tlmgr install listings
call tlmgr install minted
call tlmgr install fancyhdr
call tlmgr install glossaries
call tlmgr install ifoddpage
call tlmgr install relsize
call tlmgr install glossaries-english
call tlmgr install glossaries-german
call tlmgr install babel-vietnamese
call tlmgr install biblatex-ieee
call tlmgr install biber
call tlmgr install texcount
call tlmgr install tcolorbox
call tlmgr install environ
call tlmgr install lua-ul
call tlmgr install luacolor